name: PyLint

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [Ubuntu, Windows]

        # Run on Py3.7 and the latest release
        python-version: ['3.7', '3.x']

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      id: setup-py
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
        cache: pip
        cache-dependency-path: '**/*requirements.txt'

    - name: Install dependencies
      if: ${{ steps.setup-py.outputs.cache-hit != true }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r test-requirements.txt

    - name: Analyze code
      run: |
        pylint --rcfile=.pylintrc .
